export const englishdata = [
    {
        id: 1,
        question: "1. How frequently do you bring work home at night? ?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 3,
        marked: -1,
    },
    {
        id: 2,
        question: "2. How often do you feel you don’t have enough hours in the day to do all the things you need to do?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id:3,
        question: "3.  How often do you deny or ignore your problems in the hope that they will go away?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 4,
        question: "4. How often do you feel that there are too many deadlines in your life/work that are too difficult to meet?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 5,
        question: "5. Does mere thinking of a situation panic you?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 3,
        marked: -1,
    },
    {
        id: 6,
        question: "6. How often do you experience low self-confidence or self-esteem?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 7,
        question: "7.How frequently do you experience feelings of guilt if you relax and do nothing?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        Explaination: "If you refrain from discussing your worries, stress can be the reason.",
        correct: 1,
        marked: -1,
    },
    {
        id: 8,
        question: "8. How often find yourself thinking about problems even when you’re supposed to be relaxing?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 1,
        marked: -1,
    },
    {
        id: 9,
        question: "9. How often do you feel fatigued even after a good night’s rest?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 10,
        question: "10. How often do you eat, talk, walk, or drive quickly?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 11,
        question: "11. How often do you feel a loss of appetite or feel a desire to binge or skip meals?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 12,
        question: "12. How often do you bottle up your feelings when someone or something annoys you?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 13,
        question: "13. How frequently do you experience a lower sex drive or experience changes to your menstrual cycle?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 14,
        question: "14. How often do you find yourself grinding your teeth in annoyance?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    },
    {
        id: 15,
        question: "15. How often do you experience an increase in muscle tension and aches in the neck, lower back, head, and shoulders?",
        Options : ['NEVER','REGULARLY','RARELY', 'MOST OF THE TIME'],
        correct: 2,
        marked: -1,
    }
]